language: java
jdk:
  - oraclejdk8
script:
  - mvn verify -X -f ./pom.xml
  - mvn package
  - mvn javadoc:javadoc
  - mvn clean site
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/cobertura/coverage.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_PROJECT_TOKEN 
  - mvn versions:display-dependency-updates
  - mvn versions:display-plugin-updates